[package]
name = "nearlight_pass"
version = "0.1.0"
authors = ["Swift <github@swifteagle.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "*"
serde = "*"
